### ISSUE TITLE
'Missing script' error every start of IntelliJ

### ISSUE THREAD

**Issue by kvenn** [krasa/GrepConsole#282]
**Describe the bug**
I got some help setting up a custom extension with LivePlugin [here](https://github.com/krasa/GrepConsole/issues/47#issuecomment-1694501190).

Now, every time I restart IntelliJ I get the error toast in the screenshot below.

```
missing script 'shorten'
```

Note: I run my app, the filter doesn't work initially. Then 1 second later it starts working (so the problem solves itself?)

**To Reproduce**
1. Use LivePlugin with custom extension as the action for a filter (as show in the linked thread above)
2. Restart IntelliJ
3. You'll see "shorten registered"
4. Then right after, you'll see "missing script 'shorten'"

**Expected behavior**
There is no error

**Screenshots**
![image](https://github.com/krasa/GrepConsole/assets/1782467/7dac08eb-e4aa-4ca6-a285-45fc39ee70a2)

**Environment :**
GrepConsole: 12.20.1-IJ2021.1

**Comment by krasa** [comment]
LivePlugin might be registered too late, IntelliJ can make various consoles in the background that use this plugin. I will move the validation...

> Note: I run my app, the filter doesn't work initially. Then 1 second later it starts working (so the problem solves itself?)

strange.

**Comment by kvenn** [comment]
Thank you! Yeah I believe it's actually working, just showing the error toast too early. I can mark it as "don't show again", but I wouldn't want to hide real errors.

The 1 second seems variable. I just restarted again and it worked from the beginning (even though the error showed). I did it again, and it looks like it 1 seconds worth of log lines to start shortening. But I'm very okay with this! Was mostly flagging the error toast.

**Comment by krasa** [comment]
Thanks! Things were seriously broken, the filter was skipped while indexing :)
If it does not help, then the output might not be split into lines, you can check by doing this.
![image](https://github.com/krasa/GrepConsole/assets/1160875/0c644b72-25d0-4e4f-97b8-0030cd3859fc)
Nothing should be printed.

Also, pins should now work, it was hooked on an old API that Flutter does not use.

You can try it:
[GrepConsole-12.21.0-IJ2021.1.zip](https://github.com/krasa/GrepConsole/files/12457612/GrepConsole-12.21.0-IJ2021.1.zip)

**Comment by kvenn** [comment]
I'm still seeing the "missing script" error, but I can just mark it as "don't show again" since the action is definitely still working.
